services:
  accounts:
    image: "tiagoveri/accounts:v1"
    container_name: accounts-ms
    ports:
      - "8080:8080"
    deploy:
      resources:
        limits:
          memory: 700m
    networks:
      - tiagoveri
  loans:
    image: "tiagoveri/loans:v1"
    container_name: loans-ms
    ports:
      - "8090:8090"
    deploy:
      resources:
        limits:
          memory: 700m
    networks:
      - tiagoveri
  cards:
    image: "tiagoveri/cards:v1"
    container_name: cards-ms
    ports:
      - "9000:9000"
    deploy:
      resources:
        limits:
          memory: 700m
    networks:
      - tiagoveri
networks:
  tiagoveri:
    driver: "bridge"